# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      environment:
        description: 'Environment to test against'
        required: false
        default: 'production'
        type: choice
        options:
          - production
          - staging
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BASE_URL: ${{ secrets.BASE_URL }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Verify DATABASE_URL is set
      run: |
        if [ -z "$DATABASE_URL" ]; then
          echo "⚠️  DATABASE_URL secret is not set"
          echo "   Please add it in GitHub repository Settings > Secrets and variables > Actions"
        else
          echo "✅ DATABASE_URL is configured"
        fi
    
    - name: Test database connection
      run: |
        python erpnext_test_script.py
      continue-on-error: true
    
    - name: Run API tests
      run: |
        echo "Running API tests against ${{ inputs.environment || 'production' }} environment"
        # Add your additional test commands here
